baseURL                 = 'https://hudder.ir/'
canonifyurls            = "true"
languageCode            = 'en-us'
title                   = 'Hudder | هادر'
publishDir              = "docs"

# [permalinks]
#     about-us             = "/:section/:contentbasename/"  #why :contentbasename, why not :title? not to break the return link in shop page; Better to use another idea by coding a bit in future.
#     blog                = "/:section/:year/:month/:title/"
#     apply                 = "/:section/:contentbasename/"
#     something_else                = "/:title/"

[[cascade]]
   [cascade._target]
    path = '/camps/sample-page'
    [cascade.params]
      layout = "sample-page"
